
INSERT INTO Towns() VALUES
('Sofia'),
('Varna'),
('Plovdiv'),
('Burgas'),
('Ruse'),
('Stara Zagora'),
('Pleven'),
('Sliven'),
('Dobrich'),
('Shumen'),
('Haskovo'),
('Pazardzhik'),
('Yambol'),
('Pernik'),
('Blagoevgrad'),
('Veliko Tarnovo'),
('Vratsa'),
('Kardzhali'),
('Kyustendil'),
('Gabrovo'),
('Asenovgrad'),
('Vidin'),
('Kazanlak'),
('Montana'),
('Targovishte'),
('Dimitrovgrad'),
('Silistra'),
('Lovech'),
('Razgrad'),
('Petrich'),
('Dupnitsa'),
('Gorna Oryahovitsa'),
('Smolyan'),
('Sandanski'),
('Samokov'),
('Nova Zagora'),
('Karlovo'),
('Velingrad'),
('Sevlievo'),
('Lom'),
('Aytos'),
('Svishtov'),
('Harmanli'),
('Troyan'),
('Botevgrad'),
('Gotse Delchev'),
('Peshtera'),
('Karnobat'),
('Svilengrad'),
('Momchilgrad'),
('Panagyurishte'),
('Popovo'),
('Chirpan'),
('Rakovski'),
('Parvomay'),
('Provadia'),
('Berkovitsa'),
('Novi Pazar'),
('Radomir'),
('Ihtiman'),
('Pomorie'),
('Novi Iskar'),
('Nesebar'),
('Radnevo'),
('Balchik'),
('Razlog'),
('Byala Slatina'),
('Kozloduy'),
('Kavarna'),
('Stamboliyski'),
('Pavlikeni'),
('Isperih'),
('Mezdra'),
('Kostinbrod'),
('Etropole'),
('Bankya'),
('Knezha'),
('Elhovo'),
('Omurtag'),
('Tutrakan'),
('Ardino'),
('Lukovit'),
('Teteven'),
('Kubrat'),
('Tryavna'),
('Bansko'),
('Sredets'),
('Veliki Preslav'),
('Krichim'),
('Devnya'),
('Rakitovo'),
('Septemvri'),
('Krumovgrad'),
('Belo Pole'),
('Lyaskovets'),
('Simeonovgrad'),
('Dzhebel'),
('Dulovo'),
('Aksakovo'),
('Belene'),
('Beloslav'),
('Svoge'),
('Dryanovo'),
('Lyubimets'),
('Tervel'),
('Zlatograd'),
('Dolni Chiflik'),
('Simitli'),
('Pirdop'),
('Kuklen'),
('Slivnitsa'),
('Elin Pelin'),
('General Toshevo'),
('Devin'),
('Aydemir'),
('Kostenets'),
('Tvarditsa'),
('Straldzha'),
('Varshets'),
('Tsarevo'),
('Kotel'),
('Lozen'),
('Yakoruda'),
('Kameno'),
('Belogradchik'),
('Elena'),
('Vetovo'),
('Topolovgrad'),
('Bobov Dol'),
('Strazhitsa'),
('Riltsi'),
('Benkovski'),
('Oryahovo'),
('Chepelare'),
('Suvorovo'),
('Perushtitsa'),
('Zlatitsa'),
('Yablanovo'),
('Bozhurishte'),
('Draginovo'),
('Bistritsa'),
('Polski Trambesh'),
('Dalgopol'),
('Rozino'),
('Sozopol'),
('Dolna Banya'),
('Logodazh'),
('Koynare'),
('Trastenik'),
('Dolni Dabnik'),
('Kazichene'),
('Dve Mogili'),
('Kostandovo'),
('Ignatievo'),
('Kalipetrovo'),
('Shivachevo'),
('Varbitsa'),
('Pravets'),
('Nikopol'),
('Nedelino'),
('Slavyanovo'),
('Strelcha'),
('Glodzhevo'),
('Godech'),
('Bukovlak'),
('Letnitsa'),
('Bratsigovo'),
('Malo Konare'),
('Sapareva Banya'),
('Belovo'),
('Dyankovo'),
('Breznik'),
('Trud'),
('Smyadovo'),
('Rudozem'),
('Slivo Pole'),
('Zavet'),
('Belozem'),
('Debelets'),
('Breznitsa'),
('Ivaylovgrad'),
('Tsalapitsa'),
('Sarnitsa'),
('Marten'),
('Kresna'),
('Sungurlare'),
('Vladaya'),
('Stara Kresna'),
('Brestovene'),
('Chorbadzhiysko'),
('Iskar'),
('Yasenovets'),
('Kran'),
('Pokrovnik'),
('Dolna Mitropolia'),
('Primorsko'),
('Selanovtsi'),
('Kochan'),
('Zarnevo'),
('Vrachesh'),
('Gulyantsi'),
('Yagodovo'),
('Maglizh'),
('Valchedram'),
('Krivodol'),
('Belitsa'),
('Aleko Konstantinovo'),
('Yoakim-Gruevo'),
('Nikolaevo'),
('Shabla'),
('Dragoman'),
('Smirnenski'),
('Yasenkovo'),
('Branipole'),
('Kaolinovo'),
('Sveti Vlas'),
('Valchidol'),
('Gurkovo'),
('Ezerche'),
('Ivaylo'),
('Roman'),
('Mizia'),
('Ruen'),
('Kula'),
('Rogosh'),
('Batak'),
('Ribnovo'),
('Yagoda'),
('Topoli'),
('Trudovets'),
('Ostrovo'),
('Kalofer'),
('Kamenar'),
('Krumovo'),
('Voluyak'),
('Pancharevo'),
('Pavel Banya'),
('Banya'),
('Kableshkovo'),
('Dorkovo'),
('Koprinka'),
('Draganovo'),
('Manole'),
('Dolna Oryahovitsa'),
('Ustina'),
('Opaka'),
('Hadzhidimovo'),
('Staro Oryahovo'),
('Borino'),
('Archar'),
('Iskra'),
('Dobrinishte'),
('Yablanitsa'),
('Loznitsa'),
('Sotirya'),
('Tsonevo'),
('Bezmer'),
('Novo Selo'),
('Valkosel'),
('Zlataritsa'),
('Buhovo'),
('Bolyartsi'),
('Kalekovets'),
('Ugarchin'),
('Samuil'),
('Byala Cherkva'),
('Kliment'),
('Nova Mahala'),
('Tran'),
('Kurtovo Konare'),
('Sadovo'),
('Markovo'),
('Galata'),
('Debren'),
('German'),
('Byal Izvor'),
('Podayva'),
('Grozdyovo'),
('Novi Han'),
('Apriltsi'),
('Ognyanovo'),
('Rila'),
('Parvomaytsi'),
('Valnari'),
('Skutare'),
('Kilifarevo'),
('Glavinitsa'),
('Dospat'),
('Gluhar'),
('Satovcha'),
('Chepintsi'),
('Sevar'),
('Bregovo'),
('Branichevo'),
('Shtraklevo'),
('Kornitsa'),
('Dermantsi'),
('Rani List'),
('Sadovets'),
('Obrochishte'),
('Dabnitsa'),
('Svetovrachane'),
('Kitanchevo'),
('Startsevo'),
('Slashten'),
('Buzovgrad'),
('Enina'),
('Fotinovo'),
('Borovo'),
('Katunitsa'),
('Bratanitsa'),
('Shiroko Pole'),
('Malko Tarnovo'),
('Pristoe'),
('Tsaratsovo'),
('Sborishte'),
('Polikrayshte'),
('Koprivshtitsa'),
('Batanovtsi'),
('Chernomorets'),
('Aheloy'),
('Belovets'),
('Borovan'),
('Musomishta'),
('Isperihovo'),
('Krushare'),
('Garmen'),
('Dragichevo'),
('Semchinovo'),
('Pordim'),
('Voyvodinovo'),
('Obzor'),
('Lazhnitsa'),
('Ayrovo'),
('Tetovo'),
('Laki'),
('Harlets'),
('Chernogorovo'),
('Medovets'),
('Yahinovo'),
('Gabarevo'),
('Sheynovo'),
('Chalakovi'),
('Vladimirovtsi'),
('Gorni Dabnik'),
('Tranak'),
('Pletena'),
('Balgarovo'),
('Glavinitsa'),
('Mokrishte'),
('Gorno Prahovo'),
('Aleksandrovo'),
('Petarch'),
('Bisertsi'),
('Sinitovo'),
('Timarevo'),
('Mramor'),
('Opalchensko'),
('Suhindol'),
('Zvanichevo'),
('Oreshak'),
('Kocherinovo'),
('Veselina'),
('Most'),
('Byala Reka'),
('Polkovnik Zhelyazovo'),
('Gradezhnitsa'),
('Okorsh'),
('Popintsi'),
('Nova Cherna'),
('Brestnik'),
('Gigen'),
('Debelt'),
('Kraynitsi'),
('Smilyan'),
('Slokoshtitsa'),
('Kokalyane'),
('Radanovo'),
('Hrishteni'),
('Litakovo'),
('Chernolik'),
('Zheglartsi'),
('Malorad'),
('Resen'),
('Hristo-Danovo'),
('Barutin'),
('Kostievo'),
('Korten'),
('Chiprovtsi'),
('Karageorgievo'),
('Lehchevo'),
('Komuniga'),
('Gruevo'),
('Asenovtsi'),
('Mortagonovo'),
('Antonovo'),
('Karnalovo'),
('Iskrets'),
('Gorna Mitropolia'),
('Zgorigrad'),
('Brezovo'),
('Izgrev'),
('Vakarel'),
('Belogradets'),
('Popitsa'),
('Seliminovo'),
('Karamantsi'),
('Uzundzhovo'),
('Graf Ignatievo'),
('Stremtsi'),
('Busmantsi'),
('Merichleri'),
('Sashevo'),
('Medkovets'),
('Mogilyane'),
('Golesh'),
('Lesnovo'),
('Samoranovo'),
('Skravena'),
('Kermen'),
('Plachkovtsi'),
('Divotino'),
('Glogovo'),
('Galiche'),
('Pchelnik'),
('Lyuben Karavelovo'),
('Dolni Tsibar'),
('Muldava'),
('Kavrakirovo'),
('Milkovitsa'),
('Sredishte'),
('Ovoshtnik'),
('Stavertsi'),
('Boyantsi'),
('Venets'),
('Stroevo'),
('Maglen'),
('Dolno Osenovo'),
('Petarnitsa'),
('Bachevo'),
('Vransko'),
('Dushevo'),
('Kukorevo'),
('Zverino'),
('Bistritsa'),
('Vetren Dol'),
('Razhitsa'),
('Varbovka'),
('Kamburovo'),
('Sveta Petka'),
('Radomirtsi'),
('Stozher'),
('Gorno Sakhrane'),
('Boychinovtsi'),
('Anton'),
('Toros'),
('Yunatsite'),
('Orizare'),
('Zheleznitsa'),
('Yakimovo'),
('Ivanski'),
('Yabalchevo'),
('Dabene'),
('Trivoditsi'),
('Grivitsa'),
('Trastenik'),
('Krepcha'),
('Chelopech'),
('Osetenovo'),
('Stratsin'),
('Mirkovo'),
('Dragor'),
('Oresh'),
('Zemen'),
('Kesarevo'),
('Vazovo'),
('Tarnak'),
('Obretenik'),
('Mirovyane'),
('Gornik'),
('Alfatar'),
('Negovan'),
('Tserovo'),
('Govedare'),
('Senovo'),
('Chintulovo'),
('Zmeitsa'),
('Samovodene'),
('Feldfebel Denkovo'),
('Tenevo'),
('Tazha'),
('Dabravino'),
('Sklave'),
('Lilyache'),
('Ryahovtsite'),
('Gorski Izvor'),
('Barzia'),
('Hvostyane'),
('Krushari'),
('Krivina'),
('Obruchishte'),
('Perperek'),
('Zaychar'),
('Partizani'),
('Glava'),
('Rogach'),
('Manolich'),
('Maysko'),
('Gorna Kula'),
('Boyno'),
('Ludogortsi'),
('Ryahovo'),
('Vinogradets'),
('Leshko'),
('Dalboki'),
('Bozveliysko'),
('Byaga'),
('Duhovets'),
('Dolno Dryanovo'),
('Eleshnitsa'),
('Yonkovo'),
('Dobromirtsi'),
('Potochnitsa'),
('Orizovo'),
('Dobrovnitsa'),
('Tsarev Brod'),
('Chakalarovo'),
('Drenovets'),
('Nedan'),
('Paprat'),
('Bezhanovo'),
('Zagoriche'),
('Paisievo'),
('Kitna'),
('Gorna Malina'),
('Gramada'),
('Zvezdel'),
('Drumevo'),
('Zvanarka'),
('Malchika'),
('Lilyak'),
('Balgarski Izvor'),
('Dzherman'),
('Sokolino'),
('Zlatitrap'),
('Iskra'),
('Zhinzifovo'),
('Hayredin'),
('Koprivlen'),
('Polenitsa'),
('Semerdzhievo'),
('Mlechino'),
('Ostrov'),
('Dobromir'),
('Vaklinovo'),
('Vladimirovo'),
('Morozovo'),
('Karabunar'),
('Kobilyane'),
('Tulovo'),
('Chernevo'),
('Popovitsa'),
('Bazan'),
('Belomortsi'),
('Razhevo Konare'),
('Bozhan'),
('Golyamo Gradishte'),
('Sofronievo'),
('Zlatar'),
('Damyanitsa'),
('Benkovski'),
('Mineralni Bani'),
('Radilovo'),
('Beli Lom'),
('Baniska'),
('Kanchevo'),
('Kranevo'),
('Lopushna'),
('Staliyska Mahala'),
('Kirchevo'),
('Shipka'),
('Ahtopol'),
('Tankovo'),
('Gorno Kraishte'),
('Ruets'),
('Sipey'),
('Rezbartsi'),
('Aldomirovtsi'),
('Dinkata'),
('Kralevo'),
('Grashevo'),
('Dabnik'),
('Ustren'),
('Orehovitsa'),
('Konstantinovo'),
('Bortsi'),
('Basarbovo'),
('Zhelyazkovets'),
('Vresovo'),
('Minzuhar'),
('Kozlovets'),
('Katuntsi'),
('Marikostinovo'),
('Novachene'),
('Dolni Bogrov'),
('Pirgovo'),
('Kovachitsa'),
('Byala'),
('Visoka Polyana'),
('Takach'),
('Rudartsi'),
('Kosharitsa'),
('Starovo'),
('Dalbok Izvor'),
('Tserovishte'),
('Boyadzhik'),
('Yurukovo'),
('Varben'),
('Chavdar'),
('Bata'),
('Sindel'),
('Yabalkovo'),
('Banitsa'),
('Karapelit'),
('Tihomir'),
('Novo Selo'),
('Filaretovo'),
('Razhena'),
('Sandrovo'),
('Prelez'),
('Popgruevo'),
('Gara Lakatnik'),
('Sveshtari'),
('Belasitsa'),
('Govedartsi'),
('Balgarevo'),
('Vlado Trichkov'),
('Pokrayna'),
('Pasarel'),
('Gradets'),
('Byala Palanka'),
('Konstantin'),
('Chiflik'),
('Vaglen'),
('Sredkovets'),
('Vedrare'),
('Boboshevo'),
('Resilovo'),
('Zamfirovo'),
('Dabovo'),
('Vardun'),
('Marchaevo'),
('Momchilovtsi'),
('Sindeltsi'),
('Ruyno'),
('Prileptsi'),
('Brestnitsa'),
('Yana'),
('Lyaskovets'),
('Petlino'),
('Klisura'),
('Bolyarovo'),
('Petko Slaveykov'),
('Gorni Bogrov'),
('Dzhurovo'),
('Gavrailovo'),
('Elhovets'),
('Zidarovo'),
('Mishevsko'),
('Dimovo'),
('Patalenitsa'),
('Ekzarh-Antimovo'),
('Novo Delchevo'),
('Obitel'),
('Pisarevo'),
('Zhilentsi'),
('Tushovtsa'),
('Kichenitsa'),
('Madrevo'),
('Brusartsi'),
('Altimir'),
('Krastava'),
('Katina'),
('Dobri Dyal'),
('Rusokastro'),
('Cherniche'),
('Kaloyantsi'),
('Oborishte'),
('Karadzhalovo'),
('Novachene'),
('Dobroslavtsi'),
('Gyulyovtsa'),
('Marinka'),
('Cherven Breg'),
('Tsarevets'),
('Novachevo'),
('Hadzhievo'),
('Rasovo'),
('Zvezditsa'),
('Varbitsa'),
('Tarnicheni'),
('Gorno Dryanovo'),
('Sekulovo'),
('Zhivkovo'),
('Karadzhovo'),
('Topchiysko'),
('Voynyagovo'),
('Nanovitsa'),
('General Geshevo'),
('Kadievo'),
('Beli Vir'),
('Konche'),
('Gabare'),
('Topolitsa'),
('Mihnevo'),
('Sestrimo'),
('Rupite'),
('Pchelari'),
('Yabalkovets'),
('Ridino'),
('Plastina'),
('Nikola-Kozlevo'),
('Gabrovo'),
('Dolno Cherkovishte'),
('Kladnitsa'),
('Kolobar'),
('Stambolovo'),
('Tarnene'),
('Zhabokrat'),
('Glozhene'),
('Varbina'),
('Shishmanovo'),
('Pelin'),
('Preseka'),
('Gusla'),
('Bozhuritsa'),
('Yavornitsa'),
('Trem'),
('Klyuch'),
('Telerig'),
('Voysil'),
('Drangovo'),
('Mramoren'),
('Chomakovtsi'),
('Klikach'),
('Madara'),
('Yudelnik'),
('Spasovo'),
('Novo Selo'),
('Ivanovo'),
('Ruzhintsi'),
('Kirkovo'),
('Kaynardzha'),
('Nevestino'),
('Shiroka Laka'),
('Chuprene'),
('Boynitsa'),
('Makresh'),
('Madan'),
('Iskar'),
('Sitovo'),
('Tsenovo'),
('Byala');