spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/restaurant-reservations?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: moqtaparola1
  sql:
    init:
      mode: always

      mvc:
        hiddenmethod:
          filter:
            enabled: true


  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

cloudinary:
  api-key: 977641752662921
  api-secret: sJuxO9vfTtZ98pqHsteVyhzbnVk
  cloud-name: dln312h3o



  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
